### ISSUE TITLE
data.js

### ISSUE THREAD

**Issue by CalvinRodo** [esdc-devx/AppHub#19]
This file should not be located in the public folder it's only being used by the *.vue* file. 

The reason why serve is throwing an error is because the `dashboard-table.vue` is throwing an error is it can't figure out where that method you are calling is coming from.

It's working because you are including the file in index.html and it's getting downloaded and  loaded thus making it accessible to the components.

A better solution is to do the following: 

- [x] Move the `data.js` file under the `src` folder
- [x] Remove `data.js` include from the `index.html` file
- [x] Use a require to reference the `data.js` in the `dashboard-table.vue` file.

This removes the error and also ensures that unneccesary js code is not loaded into memory.

**Comment by s-laugh** [comment]
ties into #17
